services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    build:
      context: backend
      dockerfile: migrations.Dockerfile
    depends_on:
      - database

volumes:
  pgdata:
