services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - database_data:/var/lib/postgresql/data

  migrations:
    build:
      context: backend
      dockerfile: migrations.Dockerfile
    depends_on:
      - database

  backend:
    build: backend
    volumes:
      - recordings:/app/Data/recordings
    depends_on:
      - migrations

  frontend:
    build: frontend
    volumes:
      - static_data:/app/dist

  proxy:
    build: proxy
    ports:
      - 80:80
    volumes:
      - static_data:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  database_data:
  recordings:
  static_data:
