services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    build:
      context: backend
      dockerfile: migrations.Dockerfile
    depends_on:
      - db

  backend:
    build: backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080:8080
    depends_on:
      - migrations

volumes:
  pgdata:
