services:
  database:
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    env_file:
      - backend/.env
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s

  backend:
    build: backend
    restart: unless-stopped
    env_file:
      - backend/.env
    volumes:
      - videos:/app/public/videos
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: frontend
    volumes:
      - static-data:/app/dist

  proxy:
    build: proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - static-data:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  database-data:
  videos:
  static-data:
