services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  migrations:
    build:
      context: backend
      dockerfile: migrations.Dockerfile
    depends_on:
      - database

  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - recordings:/App/Data/recordings

  frontend:
    build: frontend
    volumes:
      - static_data:/App/dist

  proxy:
    build: proxy
    ports:
      - 80:80
    volumes:
      - static_data:/etc/nginx/html

volumes:
  database_data:
  recordings:
  static_data:
