services:
  database:
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - database-data:/var/lib/postgresql/data

  migrations:
    build:
      context: backend
      dockerfile: migrations.Dockerfile
    depends_on:
      - database

  backend:
    build: backend
    restart: unless-stopped
    volumes:
      - recordings:/app/public/recordings
    depends_on:
      - database

  frontend:
    build: frontend
    volumes:
      - static-data:/app/dist

  proxy:
    build: proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - static-data:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  database-data:
  recordings:
  static-data:
