services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pgdata:
